image: python:latest

stages:
  - check
  - test
  - deploy

check-files:
  stage: check
  before_script:
    - pip3 install pylint
  script:
    - pylint meetupselector/

test:
  stage: test
  before_script:
    - pip3 install pytest
    - pip3 install -r requirements.txt
  script:
    - python manage.py test
