image: python:latest

stages:
  - check
  - test
  - deploy

before_script:
  - pip3 install -r requirements.txt

check-files:
  stage: check
  before_script:
    - pip3 install pylint
  script:
    - pylint meetupselector/

test:
  stage: test
  before_script:
    - pip3 install pytest
  script:
    - python manage.py test
